baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'r0psteev - Security Blog'
theme = 'tailwind'
author = 'r0psteev'
copyright = 'r0psteev'
summaryLength = 70

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  subtitle = ""

  [params.header]
    logo = "logo.png"
    sticky = true

  [params.social_media]
    [[params.social_media.items]]
      enabled = true
      title = 'Github'
      icon = 'brand-github'
      link = 'https://github.com/r0psteev'